version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"  # Пробрасываем порт 3306 контейнера на порт 3307 хоста
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
